# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameter.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Para(object):
    def setupUi(self, Para):
        Para.setObjectName("Para")
        Para.resize(805, 551)
        self.c = QtWidgets.QDoubleSpinBox(Para)
        self.c.setGeometry(QtCore.QRect(310, 40, 101, 41))
        self.c.setDecimals(0)
        self.c.setMaximum(1000000.0)
        self.c.setSingleStep(1000.0)
        self.c.setProperty("value", 10000.0)
        self.c.setObjectName("c")
        self.label = QtWidgets.QLabel(Para)
        self.label.setGeometry(QtCore.QRect(30, 50, 241, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Para)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 251, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Para)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 231, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Para)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 251, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Para)
        self.label_5.setGeometry(QtCore.QRect(30, 290, 261, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Para)
        self.label_6.setGeometry(QtCore.QRect(30, 350, 261, 21))
        self.label_6.setObjectName("label_6")
        self.delta_price = QtWidgets.QDoubleSpinBox(Para)
        self.delta_price.setGeometry(QtCore.QRect(310, 100, 101, 41))
        self.delta_price.setMaximum(1.0)
        self.delta_price.setSingleStep(0.01)
        self.delta_price.setProperty("value", 0.1)
        self.delta_price.setObjectName("delta_price")
        self.alpha = QtWidgets.QDoubleSpinBox(Para)
        self.alpha.setGeometry(QtCore.QRect(310, 280, 101, 41))
        self.alpha.setSingleStep(0.01)
        self.alpha.setProperty("value", 1.25)
        self.alpha.setObjectName("alpha")
        self.o1 = QtWidgets.QDoubleSpinBox(Para)
        self.o1.setGeometry(QtCore.QRect(310, 220, 101, 41))
        self.o1.setMaximum(5.0)
        self.o1.setSingleStep(0.1)
        self.o1.setProperty("value", 0.5)
        self.o1.setObjectName("o1")
        self.o2 = QtWidgets.QDoubleSpinBox(Para)
        self.o2.setGeometry(QtCore.QRect(430, 220, 101, 41))
        self.o2.setMaximum(5.0)
        self.o2.setSingleStep(0.1)
        self.o2.setProperty("value", 0.5)
        self.o2.setObjectName("o2")
        self.o3 = QtWidgets.QDoubleSpinBox(Para)
        self.o3.setGeometry(QtCore.QRect(550, 220, 101, 41))
        self.o3.setMaximum(5.0)
        self.o3.setSingleStep(0.1)
        self.o3.setProperty("value", 0.8)
        self.o3.setObjectName("o3")
        self.o4 = QtWidgets.QDoubleSpinBox(Para)
        self.o4.setGeometry(QtCore.QRect(670, 220, 101, 41))
        self.o4.setMaximum(5.0)
        self.o4.setSingleStep(0.1)
        self.o4.setProperty("value", 0.5)
        self.o4.setObjectName("o4")
        self.w3 = QtWidgets.QDoubleSpinBox(Para)
        self.w3.setGeometry(QtCore.QRect(550, 160, 101, 41))
        self.w3.setProperty("value", 1.0)
        self.w3.setObjectName("w3")
        self.w2 = QtWidgets.QDoubleSpinBox(Para)
        self.w2.setGeometry(QtCore.QRect(430, 160, 101, 41))
        self.w2.setProperty("value", 3.0)
        self.w2.setObjectName("w2")
        self.w4 = QtWidgets.QDoubleSpinBox(Para)
        self.w4.setGeometry(QtCore.QRect(670, 160, 101, 41))
        self.w4.setProperty("value", 0.1)
        self.w4.setObjectName("w4")
        self.w1 = QtWidgets.QDoubleSpinBox(Para)
        self.w1.setGeometry(QtCore.QRect(310, 160, 101, 41))
        self.w1.setProperty("value", 3.0)
        self.w1.setObjectName("w1")
        self.beta = QtWidgets.QDoubleSpinBox(Para)
        self.beta.setGeometry(QtCore.QRect(310, 340, 101, 41))
        self.beta.setSingleStep(0.01)
        self.beta.setProperty("value", 0.3)
        self.beta.setObjectName("beta")
        self.label_7 = QtWidgets.QLabel(Para)
        self.label_7.setGeometry(QtCore.QRect(30, 420, 531, 21))
        self.label_7.setObjectName("label_7")
        self.recover = QtWidgets.QPushButton(Para)
        self.recover.setGeometry(QtCore.QRect(670, 470, 101, 41))
        self.recover.setObjectName("recover")
        self.ensure = QtWidgets.QPushButton(Para)
        self.ensure.setGeometry(QtCore.QRect(430, 470, 101, 41))
        self.ensure.setObjectName("ensure")
        self.cancel = QtWidgets.QPushButton(Para)
        self.cancel.setGeometry(QtCore.QRect(550, 470, 101, 41))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(Para)
        QtCore.QMetaObject.connectSlotsByName(Para)

    def retranslateUi(self, Para):
        _translate = QtCore.QCoreApplication.translate
        Para.setWindowTitle(_translate("Para", "参数调整"))
        self.label.setText(_translate("Para", "销量变化率目标权重"))
        self.label_2.setText(_translate("Para", "允许销售金额浮动范围"))
        self.label_3.setText(_translate("Para", "三率一面权重"))
        self.label_4.setText(_translate("Para", "三率一面理想目标"))
        self.label_5.setText(_translate("Para", "销售-投放 膨胀因子"))
        self.label_6.setText(_translate("Para", "市场反馈评分最小调节单位"))
        self.label_7.setText(_translate("Para", "【注】三率一面按“订足面、订足率、订单满足率、订购率”排序"))
        self.recover.setText(_translate("Para", "恢复默认值"))
        self.ensure.setText(_translate("Para", "确认修改"))
        self.cancel.setText(_translate("Para", "取消"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Para()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())